Watching for file changes with StatReloader
[01/Mar/2024 06:07:20] "GET /api/check_token HTTP/1.1" 200 39
[01/Mar/2024 06:07:20] "GET /api/check_token HTTP/1.1" 200 39
[01/Mar/2024 06:07:24] "OPTIONS /api/chat HTTP/1.1" 200 0
[01/Mar/2024 06:07:24] "OPTIONS /api/chat HTTP/1.1" 200 0
[01/Mar/2024 06:07:24] "GET /api/chat HTTP/1.1" 200 12
[01/Mar/2024 06:07:24] "GET /api/chat HTTP/1.1" 200 12
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:07:15
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jurisAPI/jurisbud/urls.py", line 23, in <module>
    path('api/', include('api.urls'))
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jurisAPI/api/urls.py", line 3, in <module>
    from . import views
  File "/home/jurisAPI/api/views.py", line 89, in <module>
    @parser_classes([FileUploadParser])
NameError: name 'parser_classes' is not defined
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jurisAPI/jurisbud/urls.py", line 23, in <module>
    path('api/', include('api.urls'))
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jurisAPI/api/urls.py", line 3, in <module>
    from . import views
  File "/home/jurisAPI/api/views.py", line 89, in <module>
    @parser_classes([FileUploadParser])
NameError: name 'parser_classes' is not defined
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Method Not Allowed: /api/chat/upload_prompt
[01/Mar/2024 06:19:32] "DELETE /api/chat/upload_prompt HTTP/1.1" 405 43
Internal Server Error: /api/chat/upload_prompt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/jurisAPI/api/views.py", line 92, in get_prompt_from_file
    print(request.file)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'file'
[01/Mar/2024 06:19:37] "POST /api/chat/upload_prompt HTTP/1.1" 500 100184
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:19:30
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

file:
Watching for file changes with StatReloader
Bad Request: /api/chat/upload_prompt
[01/Mar/2024 06:19:54] "POST /api/chat/upload_prompt HTTP/1.1" 400 109
Bad Request: /api/chat/upload_prompt
[01/Mar/2024 06:20:42] "POST /api/chat/upload_prompt HTTP/1.1" 400 109
Bad Request: /api/chat/upload_prompt
[01/Mar/2024 06:20:53] "POST /api/chat/upload_prompt HTTP/1.1" 400 109
Bad Request: /api/chat/upload_prompt
[01/Mar/2024 06:22:20] "POST /api/chat/upload_prompt?Content-Disposition=attachment;%20filename=test.txt HTTP/1.1" 400 109
[01/Mar/2024 06:22:46] "POST /api/chat/upload_prompt HTTP/1.1" 200 27
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:19:53
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

file:
file:
file:
file:
file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
Watching for file changes with StatReloader
Bad Request: /api/chat/upload_prompt
[01/Mar/2024 06:24:10] "POST /api/chat/upload_prompt HTTP/1.1" 400 109
/home/jurisAPI/jurisbud/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:23:15
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

this is the file:
Watching for file changes with StatReloader
Bad Request: /api/chat/upload_prompt
[01/Mar/2024 06:35:49] "POST /api/chat/upload_prompt HTTP/1.1" 400 109
[01/Mar/2024 06:35:52] "POST /api/chat/upload_prompt HTTP/1.1" 200 27
[01/Mar/2024 06:36:15] "POST /api/chat/upload_prompt HTTP/1.1" 200 27
/home/jurisAPI/jurisbud/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:35:43
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

this is the file:
this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
Watching for file changes with StatReloader
/home/jurisAPI/api/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:36:25
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/jurisAPI/api/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:38:24
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:39:07
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Internal Server Error: /api/chat/upload_prompt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/jurisAPI/api/views.py", line 95, in get_prompt_from_file
    "type": file.content_type,
AttributeError: 'dict' object has no attribute 'content_type'
[01/Mar/2024 06:39:58] "POST /api/chat/upload_prompt HTTP/1.1" 500 92803
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:39:48
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jurisAPI/jurisbud/urls.py", line 23, in <module>
    path('api/', include('api.urls'))
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jurisAPI/api/urls.py", line 3, in <module>
    from . import views
  File "/home/jurisAPI/api/views.py", line 96
    "name": file.['filename']
                 ^
SyntaxError: invalid syntax
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Internal Server Error: /api/chat/upload_prompt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/jurisAPI/api/views.py", line 95, in get_prompt_from_file
    "type": file['content_type'],
KeyError: 'content_type'
[01/Mar/2024 06:40:38] "POST /api/chat/upload_prompt HTTP/1.1" 500 92512
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:40:32
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
Watching for file changes with StatReloader
Internal Server Error: /api/chat/upload_prompt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/jurisAPI/api/views.py", line 95, in get_prompt_from_file
    "type": file.name
AttributeError: 'dict' object has no attribute 'name'
[01/Mar/2024 06:41:15] "POST /api/chat/upload_prompt HTTP/1.1" 500 92740
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:41:05
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
Watching for file changes with StatReloader
Internal Server Error: /api/chat/upload_prompt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/dist-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/utils/encoders.py", line 50, in default
    return obj.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
[01/Mar/2024 06:41:31] "POST /api/chat/upload_prompt HTTP/1.1" 500 99054
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:41:29
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jurisAPI/jurisbud/urls.py", line 23, in <module>
    path('api/', include('api.urls'))
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jurisAPI/api/urls.py", line 3, in <module>
    from . import views
  File "/home/jurisAPI/api/views.py", line 94
    for k in file.keys()
                        ^
SyntaxError: expected ':'
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jurisAPI/jurisbud/urls.py", line 23, in <module>
    path('api/', include('api.urls'))
  File "/usr/local/lib/python3.10/dist-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jurisAPI/api/urls.py", line 3, in <module>
    from . import views
  File "/home/jurisAPI/api/views.py", line 94
    for k in file.keys()
                        ^
SyntaxError: expected ':'
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
[01/Mar/2024 06:42:13] "POST /api/chat/upload_prompt HTTP/1.1" 200 22
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:42:09
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
file
Watching for file changes with StatReloader
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:42:21
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:42:37
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:43:52
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
[01/Mar/2024 06:44:14] "POST /api/chat/upload_prompt HTTP/1.1" 200 42
[01/Mar/2024 06:44:32] "POST /api/chat/upload_prompt HTTP/1.1" 200 42
/home/jurisAPI/api/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:44:11
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
Watching for file changes with StatReloader
/home/jurisAPI/api/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:44:51
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/jurisAPI/api/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:45:00
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/jurisAPI/api/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:45:11
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/jurisAPI/api/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:45:20
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:48:53
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Internal Server Error: /api/chat/upload_prompt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/jurisAPI/api/views.py", line 97, in get_prompt_from_file
    fileType = validate_file_type(file)
NameError: name 'validate_file_type' is not defined
[01/Mar/2024 06:49:34] "POST /api/chat/upload_prompt HTTP/1.1" 500 92652
/home/jurisAPI/api/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:49:31
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
Watching for file changes with StatReloader
[01/Mar/2024 06:49:49] "POST /api/chat/upload_prompt HTTP/1.1" 200 63
[01/Mar/2024 06:50:04] "POST /api/chat/upload_prompt HTTP/1.1" 200 69
/home/jurisAPI/api/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:49:48
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
this is the file:
{'file': <InMemoryUploadedFile: ef (text/plain)>}
Watching for file changes with StatReloader
/home/jurisAPI/api/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:50:37
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/jurisAPI/api/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2024 - 06:56:41
Django version 5.0.2, using settings 'jurisbud.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
